nie_gram/muzyk/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path, include, reverse_lazy
from django.views.generic import ListView, DetailView, CreateView, DeleteView, UpdateView
from . import views
from .models import Zespol, Samochod

app_name = 'muzyk'
urlpatterns = [
    path('', views.main, name='main'),
    path('fast/', views.fast, name='fast'),
    path('fast/analiza/', views.analiza, name='analiza'),
    path('fast/wycena/', views.wycena, name='wycena'),
    path('fast/podzial/', views.podzial, name='podzial'),
    path('slow/', login_required(views.slow), name='slow'),
    path('zespol-lista/', login_required(views.ZespolList.as_view(model=Zespol)), name="zespol-lista"),
    path('zespol-update/<int:pk>', login_required(views.ZespolUpdate.as_view(model=Zespol)), name="zespol-update"),
    path('zespol-detail/<int:pk>', login_required(views.ZespolDetail.as_view(model=Zespol)), name="zespol-detail"),
    path('zespol-create/', login_required(views.ZespolCreate.as_view(model=Zespol)), name="zespol-create"),
    path('zespol-delete/<int:pk>', login_required(views.ZespolDelete.as_view(model=Zespol)), name="zespol-delete"),
    path('samochod-lista/', login_required(views.SamochodList.as_view(model=Samochod)), name="samochod-lista"),
    path('samochod-update/<int:pk>', login_required(views.SamochodUpdate.as_view(model=Samochod)), name="samochod-update"),
    path('samochod-detail/<int:pk>', login_required(views.SamochodDetail.as_view(model=Samochod)), name="samochod-detail"),
    path('samochod-create/', login_required(views.SamochodCreate.as_view(model=Samochod)), name="samochod-create"),
    path('samochod-delete/<int:pk>', login_required(views.SamochodDelete.as_view(model=Samochod)), name="samochod-delete"),
]

nie_gram/nie_gram/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView



urlpatterns = [
    path('admin/', admin.site.urls),
    path('start/', include('muzyk.urls')),
    path('register/', include('register.urls')),
    path('', include('django.contrib.auth.urls')),
]

nie_gram/register/urls.py
from django.urls import path

from . import views

app_name = 'register'
urlpatterns = [
    path('register/', views.register, name="register"),
    path('index/', views.index, name="index"),
]

nie_gram/muzyk/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse

# Create your models here.
class Zespol(models.Model):
    nazwa = models.CharField(max_length=100, blank=False)
    ilosc_czlonkow = models.PositiveIntegerField()
    min_kwota_zlecenia = models.PositiveIntegerField()
    manager = models.CharField(max_length=1, choices=[
        ('P', "% wynagrodzenia"),
        ('S', "stawka [zł]"),
        ('C', "jako członek zespolu"),
        ('N', "Nie")], default='N')
    booker = models.CharField(max_length=1, choices=[
        ('P', "% wynagrodzenia"),
        ('S', "stawka [zł]"),
        ('C', "jako członek zespolu"),
        ('N', "Nie")], default='N')
    fundusz = models.CharField(max_length=1, choices=[
        ('P', "% z wynagrodzenia"),
        ('S', "określona stawka [zł]"),
        ('C', "jako członek zespolu"),
        ('N', "Nie")], default='N')
    autor = models.ForeignKey(User, on_delete=models.CASCADE)

    class Meta:
        verbose_name_plural = 'zespoły'

    def __str__(self):
        return f"{self.nazwa}"


    def get_absolute_url(self):
        return reverse('muzyk:zespol-lista')


class Samochod(models.Model):
    zespol = models.ForeignKey(Zespol,
                               on_delete=models.CASCADE,
                               related_name='samochody')
    nazwa = models.CharField(max_length=50, help_text='', blank=False)
    BENZYNA = 'B'
    DIESEL = 'D'
    LPG = 'G'
    PALIWO = (
        (BENZYNA, 'benzyna'),
        (DIESEL, 'diesel'),
        (LPG, 'gaz')
    )
    paliwo = models.CharField(max_length=1, choices=PALIWO, default=BENZYNA)
    ile_litrow_pali_na_100_km = models.DecimalField(max_digits=4, decimal_places=2, blank=False)
    autor = models.ForeignKey(User,
                              on_delete=models.CASCADE)

    class Meta:
        verbose_name_plural = 'samochody'

    def __str__(self):
        return f"{self.nazwa}"

    def get_absolute_url(self):
        return reverse('muzyk:samochod-lista')


class AnalizaLubWycenaOferty(models.Model):
    oferta = models.DecimalField(max_digits=10, decimal_places=2, blank=False, help_text="Kwota w zł.")
    podatek = models.DecimalField(max_digits=3, decimal_places=1, blank=False, help_text="Jeśli oferta to kwota netto to wpisz tutaj 0.")
    odleglosc = models.DecimalField(max_digits=5, decimal_places=2, blank=False, help_text="Odległość w km.")
    ilosc_aut = models.SmallIntegerField()
    srednie_spalanie = models.DecimalField(max_digits=4, decimal_places=2, blank=False, help_text="Spalanie w L/100km")
    srednia_cena_paliwa = models.DecimalField(max_digits=3, decimal_places=2, help_text="Cena w zł.")
    koszt_noclegu = models.DecimalField(max_digits=7, decimal_places=2, help_text="Cena w zł.")
    dodatkowe_koszty = models.DecimalField(max_digits=8, decimal_places=2)

nie_gram/register/models.py
from django.db import models

# Create your models here.

nie_gram/muzyk/forms.py
# class lizaLubWycenaOfertyForm():
#     pass
#
# form = lizaLubWycenaOfertyForm()
#
# e = lizaLubWycenaOferty.objects.get()
# {}
# form = lizaLubWycenaOfertyForm()

nie_gram/register/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class RegisterForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ["username", "email", "password1", "password2"]

nie_gram/muzyk/views.py
from django.shortcuts import render, HttpResponse
from django.views.generic import ListView, DetailView, CreateView, DeleteView, UpdateView
from django.urls import reverse_lazy

from .models import Zespol, Samochod
# Create your views here.


def index(request):
    return HttpResponse("Hello, world. You're at the muzyk index.")


def main(request):
    return render(request, 'muzyk/main.html')


def logowanie(request):
    return render(request, 'register/login.html')


def fast(request):
    return render(request, 'muzyk/fast.html')


def analiza(request):
    return render(request, 'muzyk/analiza.html')


def wycena(request):
    return render(request, 'muzyk/wycena.html')


def podzial(request):
    return render(request, 'muzyk/podzial.html')


def slow(request):
    return render(request, 'muzyk/slow.html')


class ZespolList(ListView):
    model = Zespol


class ZespolDetail(DetailView):
    model = Zespol


class ZespolCreate(CreateView):
    model = Zespol
    fields = '__all__'


class ZespolUpdate(UpdateView):
    model = Zespol
    fields = '__all__'


class ZespolDelete(DeleteView):
    model = Zespol
    success_url = reverse_lazy("muzyk:zespol-lista")


class SamochodList(ListView):
    model = Samochod


class SamochodDetail(DetailView):
    model = Samochod


class SamochodCreate(CreateView):
    model = Samochod
    fields = '__all__'


class SamochodUpdate(UpdateView):
    model = Samochod
    fields = '__all__'


class SamochodDelete(DeleteView):
    model = Samochod
    success_url = reverse_lazy("muzyk:samochod-lista")

nie_gram/register/views.py
from django.shortcuts import render, redirect
from .forms import RegisterForm

# Create your views here.
def index(request):
    return render(request, 'register/index.html')


def register(request):
    if request.method == "POST":
        form = RegisterForm(request.POST)
        if form.is_valid():
            form.save()

        return redirect("/start")
    else:
        form = RegisterForm()

    return render(request, 'registration/registration_form.html', {"form":form})

nie_gram/muzyk/templates/muzyk/analiza.html
<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
          integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    {% load static %}

    <link rel="stylesheet" type="text/css" href="{% static 'muzyk/style.css' %}">
    <meta charset="UTF-8">
    <title>Analiza oferty</title>


</head>
<body>

     <div class="container">

         <h2><b>Analiza oferty</b></h2>

         <form method="post">
             {% csrf_token %}

            <p><label>Oferta [zł] </label>
            <input type="number" min="0" name="oferta" />

            <input type="radio" name="wartosc" value="netto" id="netto" onclick="showHide()">netto
            <input type="radio" name="wartosc" value="brutto" id="brutto" onclick="showHide()" checked>brutto

            <div id="hiddenBlock">
                <label>Podatek [%]</label>
                <input type="number" min="0" max="99" name="podatek" id="podatek" />
            </div>

         <fieldset>

             <legend>Transport</legend>

             <p><label>Odległość [km] </label>
             <input type="number" required min="0" step="0.01" name="odleglosc" /></p>

             <p><label>Ilość aut </label>
             <input type="number" min="0" name="cars" />

             <p><label>Średnie spalanie [l/100km] </label>
             <input type="number" min="0" name="spalanie" /></p>

             <p><label>Średnia cena paliwa [zł] </label>
             <input type="number" min="0" name="paliwo" /></p>

         </fieldset>

         <fieldset>

             <legend>Inne</legend>

             <p><label>Koszt noclegu [zł] </label>
             <input type="number" min="0" name="hotel" /></p>

             <p><label>Dodatkowe koszta [zł] </label>
             <input type="number" min="0" name="inne" /></p>

         </fieldset>


          <p>
              <input type="button" value="Na czysto" onclick="calcWynik()" >
              <input type="text" name="wyn"><br>
          </p>
          <p>
              <input type="reset" onclick="reset" value="Wyczyść">
          </p>

          </form>
     </div>

<script>
    function showHide() {

                if(document.getElementById("netto").checked) {
                    document.getElementById("podatek").value = "0";
                    document.getElementById("hiddenBlock").style.display='none';
                } else {
                    document.getElementById("hiddenBlock").style.display='block';
                    }
            }



    function calcWynik() {
        let of = document.getElementsByName("oferta")[0].value;
        let pod = document.getElementsByName("podatek")[0].value;
        let inn = document.getElementsByName("inne")[0].value;
        let odl = document.getElementsByName("odleglosc")[0].value;
        let car = document.getElementsByName("cars")[0].value;
        let spa = document.getElementsByName("spalanie")[0].value;
        let pal = document.getElementsByName("paliwo")[0].value;
        let noc = document.getElementsByName("hotel")[0].value;

        let transport = Number(car) * Number(odl) * Number(spa) * Number(pal) / 100

        let wyn = (Number(of) *(1- (Number(pod) / 100))) - Number(inn) - Number(transport) - Number(noc);
        document.getElementsByName("wyn")[0].value = wyn;
    }

</script>

</body>
</html>

nie_gram/muzyk/templates/muzyk/fast.html
<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
          integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    {% load static %}

    <link rel="stylesheet" type="text/css" href="{% static 'muzyk/style.css' %}">
    <meta charset="UTF-8">
    <title>Szybkie obliczenia</title>
</head>
<body>
 <div class="container">
     <p></p>

<ul>
    <li><h3><a href="{% url 'muzyk:analiza' %}">Analiza Oferty</a></h3></li>
    <li><h3><a href="{% url 'muzyk:wycena' %}">Wycena zlecenia</a></h3></li>
    <li><h3><a href="{% url 'muzyk:podzial' %}">Podział złota</a></h3></li>
</ul>
 </div>
</body>
</html>

nie_gram/muzyk/templates/muzyk/main.html
<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
          integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    {% load static %}

    <link rel="stylesheet" type="text/css" href="{% static 'muzyk/style.css' %}">
    <style>
        h1,h2 {text-align: center;
            align: middle;}

        .guzik{
            position: center;
        }
    </style>
    <meta charset="UTF-8">
    <title>Cześć</title>
</head>
<body>
    {% if not user.is_authenticated %}
        <p><h1><a href="/login">Logowanie</a></h1></p>
        <p><h1><a href="{% url 'muzyk:fast' %}">Szybkie kalkulacje</a></h1></p>
    {% endif %}
    {% if user.is_authenticated %}
        <p><h1>Witaj {{ user.username }}!</h1></p>
        <div>
            <form action="/logout/">
                <input type="submit" value="Wyloguj" style="display: block; margin: auto;">
            </form>
        </div>
        <hr>
        <p><h1><a href="{% url 'muzyk:slow' %}">Kalkulacje</a></h1></p>
    {% endif %}

</body>
</html>

nie_gram/muzyk/templates/muzyk/podzial.html
<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
          integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    {% load static %}

    <link rel="stylesheet" type="text/css" href="{% static 'muzyk/style.css' %}">
    <meta charset="UTF-8">
    <title>Podział Złota</title>
</head>
<body>

    <div class="container">


        <h2><b>Podział złota</b></h2>
        <form method="post">
        {% csrf_token %}

        <label>Wynagrodzenie [zł] </label> <input type="number" min="0" name="kwota" />
        <br><label>Wielkość składu</label> <input type="number" min="0" name="osoby" />

        <fieldset>

            <legend>Poniesione koszta</legend>

            <label>Transport </label>
            <input type="number" required min="0" name="transport" />

            <br><label>Nocleg </label>
            <input type="number" min="0" name="hotel" />

            <br><label>Obsługa techniczna </label>
            <input type="number" min="0" name="obsluga" />

            <br><label>Goście</label>
            <input type="number" min="0" name="goscie" />

        </fieldset>

        <fieldset>
            <legend>Zobowiązania</legend>

            <label>Management</label>
            <input type="checkbox" name="management" id="management" onclick="showOptions1()"/>

            <div id="1" style="display:none">
                <label>% (po odliczeniu kosztów) </label>
                <input type="number" min="0" name="procent-man" id="procent-man" />

            </div>

            <input style="display:none" type="number" min="0" name="man_kw_in" id="man_kw_in" />
            <input style="display:none" type="number" min="0" name="man_kw_pr" id="man_kw_pr" />


            <label>Fundusz zespołu</label>
            <input type="checkbox" name="fundusz" id="fundusz" onclick="showOptions3()"/>

            <div id="3" style="display:none">
                <label>Kwota na fundusz[zł] </label>
                <input type="number" min="0" name="kwota-na-fundusz" id="kwota-na-fundusz" />
            </div>

        </fieldset>

            <p>
            <br><input type="button" value="Do rączki" onclick="calcWynik()" >
            <input type="text" name="wyn"><br>
            </p>
            <p>
            <input type="reset" onclick="reset" value="Wyczyść">
            </p>


        </form>
    </div>

<script>
    function showOptions1() {

        if (document.getElementById("management").checked == true){
            document.getElementById("1").style.display = "block";
            } else {
            document.getElementById("1").style.display = "none";
            document.getElementById("procent-man").value = "0"
            }
            }



    function showOptions3() {


        if (document.getElementById("fundusz").checked == true){
            document.getElementById("3").style.display = "block";
            } else {
            document.getElementById("3").style.display = "none";
            document.getElementById("kwota-na-fundusz").value = "0"
            }
            }



    function calcWynik() {
        let kwo = document.getElementsByName("kwota")[0].value;
        let os = document.getElementsByName("osoby")[0].value;
        let tran = document.getElementsByName("transport")[0].value;
        let hot = document.getElementsByName("hotel")[0].value;
        let go = document.getElementsByName("goscie")[0].value;
        let obs = document.getElementsByName("obsluga")[0].value;
        let pro = document.getElementsByName("procent-man")[0].value;
        let fun = document.getElementsByName("kwota-na-fundusz")[0].value;

        let pokosztach = Number(kwo) - Number(tran) - Number(hot) - Number(obs) - Number(go)
        let manager = Number(pokosztach) * Number(pro) / 100

        let wyn = (Number(pokosztach) - Number(manager) - Number(fun)) / Number(os)
        document.getElementsByName("wyn")[0].value = wyn;
    }

</script>


</body>
</html>

nie_gram/muzyk/templates/muzyk/samochod_confirm_delete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
          integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    {% load static %}

    <link rel="stylesheet" type="text/css" href="{% static 'muzyk/style.css' %}">
    <meta charset="UTF-8">
    <title>Czy napewno usunąć?</title>
</head>
<body>
    <div class="container">
        <p></p>
        <form method="post">
            {% csrf_token %}
            Czy napewno usunąć {{object}} ?
            <input type="submit" value="Zatwierdź">
        </form>
        <br>
        <p>Wróć do <a href="{% url 'muzyk:samochod-lista' %}">poprzedniej strony</a>.</p>
    </div>
</body>
</html>

nie_gram/muzyk/templates/muzyk/samochod_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
          integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    {% load static %}

    <link rel="stylesheet" type="text/css" href="{% static 'muzyk/style.css' %}">
    <meta charset="UTF-8">
    <title>Tworzymy samochód</title>
</head>
<body>
    <div class="container">
        <br>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p}}
            <br>
            <input type="submit" value="Zapisz">
        </form>
        <br>
        <p>Wróć do <a href="{% url 'muzyk:samochod-lista' %}">poprzedniej strony</a>.</p>
    </div>

</body>
</html>

nie_gram/muzyk/templates/muzyk/samochod_list.html
<!DOCTYPE html>
<html lang="en">
<head>
     <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
          integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    {% load static %}

    <link rel="stylesheet" type="text/css" href="{% static 'muzyk/style.css' %}">
    <meta charset="UTF-8">
    <title>Lista samochodów</title>
</head>
<body>
    <div class="container">
    <!--    Widok w stringu poprostu-->
        <h1>Samochody</h1>
        <form action="{% url 'muzyk:samochod-create' %}">
            <input type="submit" value="Dodaj">
        </form>
    <!--    MOZNA ODKOMENTOWAC TO I ZAKOMENTOWAC WSZYSTKO POD SPODEM, WTEDY JEST INNY WIDOK-->
    <!--    <ol>-->
    <!--    {% for item in object_list %}-->
    <!--        <li>{{ item.nazwa }}</li>-->
    <!--        <a href="{% url 'muzyk:samochod-update' item.id %}">Edytuj</a>-->
    <!--        <a href="{% url 'muzyk:samochod-delete' item.id %}">Usuń</a>-->
    <!--    {% endfor %}-->
    <!--    </ol>-->
    <!--    <p>Wróć do <a href="{% url 'muzyk:slow' %}">poprzedniej strony</a>.</p>-->


        <table class="table">
        <tr><th>Lp.</th><th>Nazwa</th><th>Operacje</th></tr>
        {% for p in object_list %}
        <tr>
          <td>{{ forloop.counter }}</td>
          <td><a href="{% url 'muzyk:samochod-detail' p.id %}">{{ p.nazwa }}</a></td>
          <td>
            {% if p.autor.username == user.username %}
    <!--          <a href="{% url 'muzyk:zespol-detail' p.id %}">Szczegóły</a>    albo szczegóły obok edytuj i usun albo szczegóły klikając w nazwę zespołu-->
              <a href="{% url 'muzyk:samochod-update' p.id %}">Edytuj</a>
              <a href="{% url 'muzyk:samochod-delete' p.id %}">Usuń</a>
            {% endif %}
          </td>
        </tr>
        {% endfor %}
        </table>
        <br>
        <p>Wróć do <a href="{% url 'muzyk:slow' %}">poprzedniej strony</a>.</p>
        </div>
</body>
</html>

nie_gram/muzyk/templates/muzyk/slow.html
<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
          integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    {% load static %}

    <link rel="stylesheet" type="text/css" href="{% static 'muzyk/style.css' %}">
    <meta charset="UTF-8">
    <title>Obliczenia dla zalogowanego uzytkownika</title>
</head>
<body>
    <div class="container">
    <p></p>

        <hr>
        <ul>
            <li><h3><a href="{% url 'muzyk:zespol-lista' %}">Lista zespołów</a></h3></li>
            <li><h3><a href="{% url 'muzyk:samochod-lista' %}">Lista samochodow</a></h3></li>
        </ul>
        <hr>
        <ul>
            <li><h3><a href="analiza">Analiza Oferty</a></h3></li>
            <li><h3><a href="wycena">Wycena zlecenia</a></h3></li>
            <li><h3><a href="podzial">Podział złota</a></h3></li>
        </ul>
        <hr>
    </div>
</body>
</html>

nie_gram/muzyk/templates/muzyk/zespol_confirm_delete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
          integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    {% load static %}

    <link rel="stylesheet" type="text/css" href="{% static 'muzyk/style.css' %}">
    <meta charset="UTF-8">
    <title>Czy napewno usunąć?</title>
</head>
<body>
    <div class="container">
        <p></p>
        <form method="post">
            {% csrf_token %}
            Czy napewno usunąć {{object}} ?
            <input type="submit" value="Zatwierdź">
        </form>
        <br>
        <p>Wróć do <a href="{% url 'muzyk:zespol-lista' %}">poprzedniej strony</a>.</p>
    </div>
</body>
</html>

nie_gram/muzyk/templates/muzyk/zespol_list.html
<!DOCTYPE html>
<html lang="en">
<head>
     <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
          integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    {% load static %}

    <link rel="stylesheet" type="text/css" href="{% static 'muzyk/style.css' %}">
    <meta charset="UTF-8">
    <title>Lista Zespolow</title>
</head>
<body>
    <div class="container">
    <!--    Widok w stringu poprostu-->
        <h1>Zespoły</h1>
        <p></p>
        <form action="{% url 'muzyk:zespol-create' %}">
            <input type="submit" value="Dodaj">
        </form>
    <!--    <ol>-->
    <!--    {% for item in object_list %}-->
    <!--        <li>{{item}}</li>-->
    <!--        <a href="{% url 'muzyk:zespol-update' item.id %}">Edytuj</a>-->
    <!--        <a href="{% url 'muzyk:zespol-delete' item.id %}">Usuń</a>-->
    <!--    {% endfor %}-->
    <!--    </ol>-->

    <!--    Widok w tabeli-->
        <table class="table">
        <tr><th>Lp.</th><th>Nazwa</th><th>Operacje</th></tr>
        {% for p in object_list %}
        <tr>
          <td>{{ forloop.counter }}</td>
          <td><a href="{% url 'muzyk:zespol-detail' p.id %}">{{ p.nazwa }}</a></td>
          <td>
            {% if p.autor.username == user.username %}
    <!--          <a href="{% url 'muzyk:zespol-detail' p.id %}">Szczegóły</a>    albo szczegóły obok edytuj i usun albo szczegóły klikając w nazwę zespołu-->
              <a href="{% url 'muzyk:zespol-update' p.id %}">Edytuj</a>
              <a href="{% url 'muzyk:zespol-delete' p.id %}">Usuń</a>
            {% endif %}
          </td>
        </tr>
        {% endfor %}
        </table>
        <br>
        <p>Wróć do <a href="{% url 'muzyk:slow' %}">poprzedniej strony</a>.</p>
    </div>
</body>
</html>

nie_gram/register/templates/register/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
          integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    {% load static %}

    <link rel="stylesheet" type="text/css" href="{% static 'muzyk/style.css' %}">
    <style>
        h1 {text-align: center;
            align: middle;}
    </style>
    <meta charset="UTF-8">
    <title>Strona logowania</title>
</head>
<body>
    <ul>
        {% if not user.is_authenticated %}
            <li><a href='/login'>Zaloguj się</a></li>
            <li><a href="{% url 'register:register' %}">Utwórz konto</a></li>
            <li><a href='/logout'>Wyloguj się</a></li>
        {% endif %}
    </ul>
</body>
</html>

nie_gram/register/templates/register/logout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Logout</title>
</head>
<body>
    <h1>Wylogowanie</h1>
    <p>Zostałeś wylogowany!</p>
</body>
</html>